on:
  workflow_dispatch
jobs:
  my_job:
    name: deploy to staging
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew nativeCompile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-tool
          path: D:\a\ffmpeg-tool\ffmpeg-tool\build\native\nativeCompile\ffmpeg-tool.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
         files: ${{github.workspace}}\a\ffmpeg-tool\ffmpeg-tool\build\native\nativeCompile\ffmpeg-tool.exe
         tag_name: 0.0.1
