on:
  workflow_dispatch
jobs:
  build_job:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Windows Execute Gradle build
        if: matrix.os == 'windows-latest'
        run: ./gradlew nativeCompile
      - name: Execute Gradle build
        if: matrix.os != 'windows-latest'
        run: |
         chmod +x gradlew
         ./gradlew nativeCompile
      - name: Windows Release
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v0.1.13
        with:
         files: ${{github.workspace}}\build\native\nativeCompile\ffmpeg-tool\ffmpeg-tool.exe
         tag_name: 0.0.1
      - name: Release
        if: matrix.os != 'windows-latest'
        uses: softprops/action-gh-release@v0.1.13
        with:
         files: ${{github.workspace}}/build/native/nativeCompile/ffmpeg-tool/**
         tag_name: 0.0.1
